### PR TITLE
cclient: fixed asan failure.

### LINKED ISSUE #330: ASAN failure: //cclient/serialization:test_json
```
Executing tests from //cclient/serialization:test_json
-----------------------------------------------------------------------------
=================================================================
==15==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000af9 at pc 0x7f2887219c5f bp 0x7fffe09688d0 sp 0x7fffe0968060
WRITE of size 10 at 0x602000000af9 thread T0
    #0 0x7f2887219c5e in vsprintf (/lib64/libasan.so.5+0x4fc5e)
    #1 0x7f2887219fde in sprintf (/lib64/libasan.so.5+0x4ffde)
    #2 0x7f2887182b1c in int_array_to_string cclient/types/types.c:125
    #3 0x7f288718f7aa in get_balances_res_balances_at cclient/response/get_balances.c:29
    #4 0x4070ca in test_deserialize_get_balances cclient/serialization/tests/test_json.c:470
    #5 0x7f28870f2447 in UnityDefaultTestRun external/unity/src/unity.c:1339
    #6 0x408e5f in main cclient/serialization/tests/test_json.c:705
    #7 0x7f2886c4a412 in __libc_start_main (/lib64/libc.so.6+0x24412)
    #8 0x40342d in _start (/home/th0br0/.cache/bazel/_bazel_th0br0/5415dad8b2251828abd8248f176274e2/execroot/org_iota_entangled/bazel-out/k8-fastbuild/bin/cclient/serialization/test_json+0x40342d)

0x602000000af9 is located 0 bytes to the right of 9-byte region [0x602000000af0,0x602000000af9)
allocated by thread T0 here:
    #0 0x7f28872b9848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
    #1 0x7f2887182a6a in int_array_to_string cclient/types/types.c:122
    #2 0x7f288718f7aa in get_balances_res_balances_at cclient/response/get_balances.c:29
    #3 0x4070ca in test_deserialize_get_balances cclient/serialization/tests/test_json.c:470
    #4 0x7f28870f2447 in UnityDefaultTestRun external/unity/src/unity.c:1339
    #5 0x408e5f in main cclient/serialization/tests/test_json.c:705
    #6 0x7f2886c4a412 in __libc_start_main (/lib64/libc.so.6+0x24412)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.5+0x4fc5e) in vsprintf
Shadow bytes around the buggy address:
  0x0c047fff8100: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff8110: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fa
  0x0c047fff8120: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c047fff8130: fa fa fd fd fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c047fff8140: fa fa 00 00 fa fa fd fd fa fa fd fd fa fa fd fd
=>0x0c047fff8150: fa fa fd fd fa fa 00 00 fa fa 00 00 fa fa 00[01]
  0x0c047fff8160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8170: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff81a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==15==ABORTING
```

### PR DESCRIPTION
**Pull request by oopsmonk**
This PR fixed #330 

# Test Plan:
CI must pass

### CODE REVIEW

File: cclient/response/get_balances.c [hunk 1]
```diff
@@ -10,25 +10,24 @@
 get_balances_res_t* get_balances_res_new() {
   get_balances_res_t* res =
       (get_balances_res_t*)malloc(sizeof(get_balances_res_t));
-
-  res->balances = int_array_array_new();
-  res->milestone = flex_hash_array_new();
+  if (res) {
```
Comment (tsvisabo) [inline cclient/response/get_balances.c:13]: is it possible that this function will return `retcode_t` and return OOM if malloc fails?
or do you check it on the caller side?

**Review by tsvisabo — CHANGES_REQUESTED** [review]

File: cclient/response/get_balances.c (hunk 1 above)
Comment (oopsmonk) [reply cclient/response/get_balances.c:13]: IMO, it's no difference in returning retcode_t or pointer, both need to check OOM but in the different aspect in this case. If you prefer retcode_t we can do it in all similar functions in another PR to make sure the consistency.

Comment (tsvisabo) [reply cclient/response/get_balances.c:13]: ok, cool

**Review by tsvisabo — APPROVED** [review]
