### PR TITLE
mobile: fix warnings

### LINKED ISSUE #1223: mobile: fix warnings
`bazel build -c opt //mobile/...`
and/or
`bazel test -c opt //mobile/...`

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes #1223

### CODE REVIEW

**Comment by thibault-martinez** [comment]
@rajivshah3 Does that look good to you ?

**Review by tsvisabo — DISMISSED** [review]

File: mobile/ios/Interface.mm [hunk 1]
```diff
@@ -61,7 +61,7 @@ + (NSArray*)iota_ios_pow_bundle:(NSArray*)txsTrytes trunk:(NSString*)trunk branc
   flex_trit_t flexTrunk[FLEX_TRIT_SIZE_243];
   flex_trit_t flexBranch[FLEX_TRIT_SIZE_243];
   NSMutableArray* outputTxsTrytes = [NSMutableArray array];
-  NSMutableString* outputTxsTrytesSerialized = @"";
+  NSMutableString* outputTxsTrytesSerialized;
```
Comment (rajivshah3) [inline mobile/ios/Interface.mm]: Does it give a warning if you do this?

```suggestion
  NSMutableString* outputTxsTrytesSerialized = [NSMutableString string];
```

**Review by rajivshah3 — APPROVED** [review]

**Review by tsvisabo — APPROVED** [review]
