### PR TITLE
cclient: fixed-sized trits uses flex_trit_t.

### LINKED ISSUE #410: CClient: for a fixed-sized trits uses flex_trit_t instead of trit_array_p.
- [x] attach_to_tangle
- [x] broadcast_transactions
- [x] check_consistency
- [x] get_inclusion_state
- [x] get_trytes
- [x] store_transactions
- [x] get_tips

### PR DESCRIPTION
**Pull request by oopsmonk**
This PR fixed #410 

# Test Plan:
CI must pass

### CODE REVIEW

File: ciri/api/api.c [hunk 1]
```diff
@@ -99,32 +99,39 @@ retcode_t iota_api_get_trytes(iota_api_t const *const api,
...
     return RC_API_MAX_GET_TRYTES;
   }
-  LL_FOREACH(req->hashes, iter) {
+  CDL_FOREACH(req->hashes, iter) {
     hash_pack_reset(&pack);
+    // flex_trit to trit_array_p for iota_tangle_transaction_load
+    tmp_trits = trit_array_new_from_flex(iter->hash, NUM_TRITS_HASH,
+                                         FLEX_TRIT_SIZE_243);
+    if (!tmp_trits) {
+      return RC_API_NULL_POINTER;
```
Comment (th0br0) [inline ciri/api/api.c]: this should return an OUT_OF_MEMORY error?

File: common/trinary/trit_array.c [hunk 2]
```diff
@@ -113,6 +113,29 @@ trit_array_p trit_array_new_from_trytes(tryte_t const *const trytes) {
   return trit_array;
 }
 
+trit_array_p trit_array_new_from_flex(flex_trit_t const *const trits,
+                                      size_t num_trits, size_t num_bytes) {
+  trit_array_p trit_array;
+  trit_array = (trit_array_p)malloc(sizeof(struct _trit_array));
```
Comment (th0br0) [inline common/trinary/trit_array.c]: use `calloc`

File: common/trinary/trit_array.c [hunk 3]
```diff
@@ -113,6 +113,29 @@ trit_array_p trit_array_new_from_trytes(tryte_t const *const trytes) {
...
+  if (!trit_array) {
+    // errno = IOTA_OUT_OF_MEMORY
+    return NULL;
+  }
+  memset(trit_array, 0, sizeof(struct _trit_array));
```
Comment (th0br0) [inline common/trinary/trit_array.c]: not needed with `calloc`

File: ciri/api/api.c [hunk 4]
```diff
@@ -99,32 +99,39 @@ retcode_t iota_api_get_trytes(iota_api_t const *const api,
...
 
-  if (flex_hash_array_count(req->hashes) > api->conf.max_get_trytes) {
+  if (hash243_queue_count(&req->hashes) > api->conf.max_get_trytes) {
     return RC_API_MAX_GET_TRYTES;
   }
-  LL_FOREACH(req->hashes, iter) {
+  CDL_FOREACH(req->hashes, iter) {
     hash_pack_reset(&pack);
+    // flex_trit to trit_array_p for iota_tangle_transaction_load
+    tmp_trits = trit_array_new_from_flex(iter->hash, NUM_TRITS_HASH,
```
Comment (th0br0) [inline ciri/api/api.c]: we should use a hash243_queue here and not a trit_array?

**Review by th0br0 — CHANGES_REQUESTED** [review]

File: cclient/serialization/json/json_serializer.c [hunk 5]
```diff
@@ -344,6 +344,32 @@ static retcode_t hash81_queue_to_json_array(hash81_queue_t queue,
...
+                                              char const* const obj_name,
+                                              hash8019_queue_t* queue) {
+  retcode_t ret_code = RC_OK;
+  cJSON* json_item = cJSON_GetObjectItemCaseSensitive(obj, obj_name);
+  if (cJSON_IsArray(json_item)) {
+    cJSON* current_obj = NULL;
+    cJSON_ArrayForEach(current_obj, json_item) {
+      if (current_obj->valuestring != NULL) {
+        trit_array_p tmp_ref =
+            trit_array_new_from_trytes((tryte_t*)current_obj->valuestring);
```
Comment (thibault-martinez) [inline cclient/serialization/json/json_serializer.c]: Can't you just use `flex_trits_from_trytes` instead of `trit_array_new_from_trytes ` ?

File: cclient/serialization/tests/test_json.c [hunk 6]
```diff
@@ -352,13 +352,16 @@ void test_serialize_get_trytes(void) {
   char_buffer_t* serializer_out = char_buffer_new();
   init_json_serializer(&serializer);
   get_trytes_req_t* req = get_trytes_req_new();
-  get_trytes_req_add_hash(req, TEST_81_TRYRES_1);
+  trit_array_p tmp_hash =
+      trit_array_new_from_trytes((tryte_t*)TEST_81_TRYRES_1);
```
Comment (thibault-martinez) [inline cclient/serialization/tests/test_json.c]: Dito

File: ciri/api/api.c (hunk 4 above)
Comment (thibault-martinez) [inline ciri/api/api.c]: Use a static alocated `trit_array_t` and just set `.trits = iter->hash`, i.e. no dynamic allocation nor `memcpy` needed

Comment (thibault-martinez) [reply ciri/api/api.c]: See example here: https://github.com/iotaledger/entangled/blob/develop/ciri/api/api.c#L176

File: ciri/api/tests/test_get_trytes.c [hunk 7]
```diff
@@ -49,18 +49,20 @@ void test_get_trytes_not_found(void) {
 
   api.conf.max_get_trytes = 100;
 
-  get_trytes_req_add_hash(req, NULL_HASH);
+  trit_array_p null_hash = trit_array_new_from_trytes(NULL_HASH);
```
Comment (thibault-martinez) [inline ciri/api/tests/test_get_trytes.c]: No need for `trit_array_p`

File: ciri/api/tests/test_get_trytes.c [hunk 8]
```diff
@@ -83,10 +85,14 @@ void test_get_trytes_max(void) {
 
   // Getting trytes 1 & 2 from hashes
 
-  get_trytes_req_add_hash(req, TX_1_OF_4_HASH);
-  get_trytes_req_add_hash(req, TX_2_OF_4_HASH);
+  trit_array_p tx1_hash = trit_array_new_from_trytes(TX_1_OF_4_HASH);
+  trit_array_p tx2_hash = trit_array_new_from_trytes(TX_2_OF_4_HASH);
```
Comment (thibault-martinez) [inline ciri/api/tests/test_get_trytes.c]: Dito

File: common/trinary/trit_array.c [hunk 9]
```diff
@@ -113,6 +113,29 @@ trit_array_p trit_array_new_from_trytes(tryte_t const *const trytes) {
   return trit_array;
 }
 
+trit_array_p trit_array_new_from_flex(flex_trit_t const *const trits,
```
Comment (thibault-martinez) [inline common/trinary/trit_array.c]: Not sure this function is really needed following my comments

**Review by thibault-martinez — CHANGES_REQUESTED** [review]

File: ciri/api/api.c (hunk 4 above)
Comment (oopsmonk) [reply ciri/api/api.c]: I should put a FIXME here. 
For fixing it, @thibault-martinez could you provide something like `iota_tangle_transaction_load` accept `flex_trits` or `hash243_queue`?

File: common/trinary/trit_array.c (hunk 9 above)
Comment (oopsmonk) [reply common/trinary/trit_array.c]: No needed, if `iota_tangle_transaction_load` accept flex_trit.

File: ciri/api/api.c (hunk 4 above)
Comment (thibault-martinez) [reply ciri/api/api.c]: I agree that it would be handy and I have thought about it.
The issue is that by accepting `flex_trit_t *` we lose the size attribute hence genericity. 
In the meantime, I really think there's no need for dynamic allocation here.

File: common/trinary/trit_array.c (hunk 9 above)
Comment (thibault-martinez) [reply common/trinary/trit_array.c]: Understood, but what I meant was that we could achieve the exact same thing with no dynamic allocation and no memcpy.

File: ciri/api/api.c (hunk 4 above)
Comment (oopsmonk) [reply ciri/api/api.c]: I thought `iota_tangle_transaction_load` will take `flex_trit_t`, so `trit_array_new_from_flex` is a temporary implementation which keeps code clean and can be removed easily. 
If `flex_trit_t` is not a plan for `iota_tangle_transaction_load`, I should change code here.

File: ciri/api/tests/test_get_trytes.c [hunk 10]
```diff
@@ -46,11 +46,11 @@ void test_get_trytes_not_found(void) {
   get_trytes_req_t *req = get_trytes_req_new();
   get_trytes_res_t *res = get_trytes_res_new();
   tryte_t tx_trytes[NUM_TRYTES_SERIALIZED_TRANSACTION];
+  flex_trit_t null_hash[FLEX_TRIT_SIZE_243] = {FLEX_TRIT_NULL_VALUE};
```
Comment (thibault-martinez) [inline ciri/api/tests/test_get_trytes.c]: This is not initializing all the values to `FLEX_TRIT_NULL_VALUE`, only the first one then zeros all the others.

**Review by thibault-martinez — CHANGES_REQUESTED** [review]

File: ciri/api/tests/test_get_trytes.c (hunk 10 above)
Comment (oopsmonk) [reply ciri/api/tests/test_get_trytes.c]: oops, thanks.

File: cclient/request/attach_to_tangle.c [hunk 11]
```diff
@@ -12,39 +12,53 @@ attach_to_tangle_req_t* attach_to_tangle_req_new() {
...
+  *req = NULL;
 }
 
 retcode_t attach_to_tangle_req_set_trunk(attach_to_tangle_req_t* req,
-                                         const char* trunk) {
-  return trytes_to_flex_hash(req->trunk, trunk);
+                                         tryte_t const* const trunk) {
+  size_t len = flex_trits_from_trytes(req->trunk, NUM_TRITS_HASH, trunk,
+                                      NUM_TRYTES_HASH, NUM_TRYTES_HASH);
+  return len ? RC_OK : RC_CCLIENT_FLEX_TRITS;
```
Comment (thibault-martinez) [inline cclient/request/attach_to_tangle.c]: You can go further and check that `len  == NUM_TRYTES_HASH `

File: cclient/request/attach_to_tangle.c [hunk 12]
```diff
@@ -12,39 +12,53 @@ attach_to_tangle_req_t* attach_to_tangle_req_new() {
...
 }
 
 retcode_t attach_to_tangle_req_set_branch(attach_to_tangle_req_t* req,
-                                          const char* branch) {
-  return trytes_to_flex_hash(req->branch, branch);
+                                          tryte_t const* const branch) {
+  size_t len = flex_trits_from_trytes(req->branch, NUM_TRITS_HASH, branch,
+                                      NUM_TRYTES_HASH, NUM_TRYTES_HASH);
+  return len ? RC_OK : RC_CCLIENT_FLEX_TRITS;
```
Comment (thibault-martinez) [inline cclient/request/attach_to_tangle.c]: You can go further and check that `len == NUM_TRYTES_HASH`

File: cclient/request/attach_to_tangle.c [hunk 13]
```diff
@@ -12,39 +12,53 @@ attach_to_tangle_req_t* attach_to_tangle_req_new() {
...
+retcode_t attach_to_tangle_req_add_trytes(attach_to_tangle_req_t* req,
+                                          tryte_t const* const trytes) {
+  flex_trit_t trits[FLEX_TRIT_SIZE_8019];
+  size_t len = flex_trits_from_trytes(trits, NUM_TRITS_SERIALIZED_TRANSACTION,
+                                      trytes, NUM_TRYTES_SERIALIZED_TRANSACTION,
+                                      NUM_TRYTES_SERIALIZED_TRANSACTION);
+  if (len) {
+    hash8019_queue_push(&req->trytes, trits);
+  }
+  return len ? RC_OK : RC_CCLIENT_FLEX_TRITS;
```
Comment (thibault-martinez) [inline cclient/request/attach_to_tangle.c]: You can go further and check that `len == NUM_TRYTES_SERIALIZED_TRANSACTION `

File: cclient/request/broadcast_transactions.c [hunk 14]
```diff
@@ -22,14 +22,20 @@ void broadcast_transactions_req_free(broadcast_transactions_req_t** const req) {
...
-  req->trytes = flex_hash_array_append(req->trytes, trytes);
-  return req;
+  flex_trit_t trits[FLEX_TRIT_SIZE_8019];
+  size_t len = flex_trits_from_trytes(trits, NUM_TRITS_SERIALIZED_TRANSACTION,
+                                      trytes, NUM_TRYTES_SERIALIZED_TRANSACTION,
+                                      NUM_TRYTES_SERIALIZED_TRANSACTION);
+  if (len) {
+    hash8019_queue_push(&req->trytes, trits);
+  }
+  return len ? RC_OK : RC_CCLIENT_FLEX_TRITS;
```
Comment (thibault-martinez) [inline cclient/request/broadcast_transactions.c]: Same check applies for this and all following

File: cclient/request/broadcast_transactions.h [hunk 15]
```diff
@@ -16,12 +16,12 @@ extern "C" {
 
 typedef struct broadcast_transactions_req_s {
   // List of raw transactions data to be broadcasted
-  flex_hash_array_t* trytes;
+  hash8019_queue_t trytes;
```
Comment (thibault-martinez) [inline cclient/request/broadcast_transactions.h]: I think order does not matter for this call, you can use a stack for lower memory impact.

File: cclient/request/get_trytes.c [hunk 16]
```diff
@@ -20,17 +20,15 @@ void get_trytes_req_free(get_trytes_req_t** const req) {
...
+  free(*req);
   *req = NULL;
 }
 
-get_trytes_req_t* get_trytes_req_add_hash(get_trytes_req_t* const req,
-                                          tryte_t const* const hash) {
-  req->hashes = flex_hash_array_append(req->hashes, hash);
-  return req;
+retcode_t get_trytes_req_add_hash(get_trytes_req_t* const req,
+                                  flex_trit_t const* const hash) {
```
Comment (thibault-martinez) [inline cclient/request/get_trytes.c]: Why are some `_*add` functions taking trytes and some flex_trits ?

File: cclient/request/store_transactions.h [hunk 17]
```diff
@@ -16,13 +16,13 @@ extern "C" {
 
 typedef struct store_transactions_req_s {
   // List of raw transactions data to be stored
-  flex_hash_array_t* trytes;
+  hash8019_queue_t trytes;
```
Comment (thibault-martinez) [inline cclient/request/store_transactions.h]: Order does not matter as well, maybe use a stack ?

**Review by thibault-martinez — CHANGES_REQUESTED** [review]

File: cclient/request/attach_to_tangle.c (hunk 11 above)
Comment (oopsmonk) [reply cclient/request/attach_to_tangle.c]: `flex_trits_from_trytes` returns `0` or a specific tryte number(depended on `num_trytes`) only, and `0` means error.

File: cclient/request/get_trytes.c (hunk 16 above)
Comment (oopsmonk) [reply cclient/request/get_trytes.c]: the main idea is the request/response should take flex_trit_t, but `tyrtes` is provided for the convenience in test cases at json_serializer and ciri api. I think this function should be removed or changed it to take `tyrtes` for consistency.

File: cclient/request/store_transactions.h (hunk 17 above)
Comment (oopsmonk) [reply cclient/request/store_transactions.h]: sure, thanks :-)

File: cclient/request/attach_to_tangle.c (hunk 11 above)
Comment (thibault-martinez) [reply cclient/request/attach_to_tangle.c]: My mistake sorry, I thought it could return a number different than `num_trytes`.

**Review by th0br0 — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
