### PR TITLE
common/trinary: fix long_to_trits fails for very large integer values

### LINKED ISSUE #375: long_to_trits fails for very large integer values
The `min_trits` and `long_to_trits` conversion functions fail for very large positive or negative values, such as 0x7FFFFFFFFFFFFFFF and 0x8000000000000000

### PR DESCRIPTION
**Pull request by ifullgaz**
common/trinary: fix long_to_trits fails for very large integer values (resolves #375 )

# Test Plan:
Usual test plan

### CODE REVIEW

**Review by tsvisabo — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]

File: common/trinary/trit_long.c [hunk 1]
```diff
@@ -29,22 +29,37 @@ static double const pow27LUT[] = {1,
...
+  size_t end = num_trits;
   while (end-- > 0) {
-    accum = accum * RADIX + trit[end];
+    accum = accum * RADIX + trits[end];
   }
   return accum;
 }
 
 size_t min_trits(int64_t const value) {
+  printf("Value: %lld\n", value);
```
Comment (th0br0) [inline common/trinary/trit_long.c]: remove these debug statements please

**Review by th0br0 — CHANGES_REQUESTED** [review]

File: common/trinary/trit_long.c (hunk 1 above)
Comment (ifullgaz) [reply common/trinary/trit_long.c]: Sure, I'm debugging right now because it's failing with -c opt...

File: common/trinary/trit_long.c [hunk 2]
```diff
@@ -56,7 +59,7 @@ size_t long_to_trits(int64_t const value, trit_t *const trits) {
 
   negative = value < 0;
   size = min_trits(value);
-  int64_t v_abs = negative ? -value : value;
+  uint64_t v_abs = (uint64_t)value;
```
Comment (th0br0) [inline common/trinary/trit_long.c]: You should use `llabs` here. While not ideal, casting a negative value to an int64 is not equal to its absolute value

**Review by th0br0 — CHANGES_REQUESTED** [review]

**Review by th0br0 — APPROVED** [review]
